### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by Organizer21** [xyhtac/postgres_table_recovery#1]
Just gave this script a go thinking it would be my solution as I expect quite a few rows with issues in a larger DB. However the process was killed after a good while with an OOM error in the logs. Not sure if anything can be done or improved.

```
Checking range: 0 -- 27708091
Killed
```

Kern.log
```
[284746.030034] Out of memory: Kill process 20141 (perl) score 913 or sacrifice child
[284746.120599] Killed process 20141 (perl) total-vm:31983564kB, anon-rss:30941832kB, file-rss:0kB, shmem-rss:0kB
[284748.193710] oom_reaper: reaped process 20141 (perl), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by xyhtac** [comment]
Thank you for your report.

Could you please provide some additional info to help me to reproduce your environment?

1. Perl version, postgres version
2. Row count of your big table (27708091 probably?)

Then, run script with $verbose = 1; variable set and share result if any.

Regards

**Comment by Organizer21** [comment]
Hi there, just tried this freshly so presumably the latest perl wise at least but then again no expert, had to run some extra installs on top of the one line provided by you, I think apt-get install libdbd-pg-perl and sudo apt-get install libpq-dev (not sure if both where needed for me). In either case perl and pgsql reports:

`This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi`
`psql (10.22 (Ubuntu 10.22-0ubuntu0.18.04.1))
`

Yes, that's the detected and correct row count for the table. I tried with verbose as well but it locks up and never completes the first CHECKING LOWER process. Server has 32GB RAM, script claims most of that in the first hour or so, it seems to just expand and keep things in memory and ultimately then get terminated.

**Comment by Organizer21** [comment]
For reference. attempting to run batches of 2 million records at the moment, which takes from around 280s to 480s

```
Checking range: 11000000 -- 13000000
CHECKING LOWER: 11000000 ... 12000000  LIMIT:1000000
CHECKING UPPER: 12000000 ... 13000000 LIMIT:1000000

SCAN COMPLETE IN 483 S
found 0 corrupted rows. 3 database queries performed.
```

**Comment by forall** [comment]
I have the same problem with out of memory...

 `./pg_table_recovery.pl` 
`Checking range: 0 -- 248219`
`CHECKING LOWER: 0 ... 124109  LIMIT:124109 `
Killed

`Jan 20 18:29:15 db-test kernel: Out of memory: Kill process 18950 (pg_table_recove) score 908 or sacrifice child
Jan 20 18:29:15 db-test kernel: Killed process 18950 (pg_table_recove) total-vm:4919856kB, anon-rss:2753616kB, file-rss:0kB, shmem-rss:0kB`

`
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
CentOS Linux release 7.9.2009 (Core)`

**Comment by xyhtac** [comment]
Updated **dbi_query** function to aggregate SELECT results with COUNT. Mem usage should be reduced. Your feedback is appreciated.
